"""create table

Revision ID: 24a23a5c1748
Revises: 
Create Date: 2024-06-12 22:13:21.026110

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "24a23a5c1748"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "calc_result",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("a", sa.Integer(), nullable=False),
        sa.Column("b", sa.Integer(), nullable=False),
        sa.Column("op", sa.Enum("ADD", "SUB", "MUL", "DIV", name="operation"), nullable=False),
        sa.Column("result", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("calc_result")
    # ### end Alembic commands ###
